# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/184UufvnRE3O62cPmhH27072TsAKnZhkl
"""

from google.colab import files
uploaded = files.upload()

import os
print(os.listdir())

import zipfile, os
with zipfile.ZipFile("Nail_Datasets.zip", 'r') as zip_ref:
    zip_ref.extractall("/content/nail_dataset")
print("Extracted!")
print(os.listdir("/content/nail_dataset"))

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import cv2
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
print("TF:", tf.__version__, "| GPU:", tf.config.list_physical_devices('GPU'))

import os

DATASET_PATH = "/content/nail_dataset"
IMG_SIZE = (224, 224)
BATCH_SIZE = 32
NUM_CLASSES = 7
TRAIN_DIR = os.path.join(DATASET_PATH, "train")
VAL_DIR   = os.path.join(DATASET_PATH, "val")
TEST_DIR  = os.path.join(DATASET_PATH, "test")

train_datagen = tf.keras.preprocessing.image.ImageDataGenerator(
    preprocessing_function=preprocess_input, rotation_range=25, width_shift_range=0.15,
    height_shift_range=0.15, shear_range=0.1, zoom_range=0.2, brightness_range=[0.8,1.2],
    horizontal_flip=True, fill_mode="nearest")
val_test_datagen = tf.keras.preprocessing.image.ImageDataGenerator(preprocessing_function=preprocess_input)

train_gen = train_datagen.flow_from_directory(TRAIN_DIR, target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode="categorical", shuffle=True, seed=42)
val_gen = val_test_datagen.flow_from_directory(VAL_DIR, target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode="categorical", shuffle=False)
test_gen = val_test_datagen.flow_from_directory(TEST_DIR, target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode="categorical", shuffle=False)
class_names = list(train_gen.class_indices.keys())
print("Classes:", class_names)

def detect_nail_region(img):
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    mask = cv2.inRange(hsv, np.array([0,10,60]), np.array([30,150,255]))
    k = np.ones((7,7), np.uint8)
    mask = cv2.morphologyEx(cv2.morphologyEx(mask, cv2.MORPH_CLOSE, k), cv2.MORPH_OPEN, k)
    cnts, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    h_i, w_i = img.shape[:2]
    if not cnts: return 0,0,w_i,h_i
    c = max(cnts, key=cv2.contourArea)
    if cv2.contourArea(c) < 0.05*(w_i*h_i): return 0,0,w_i,h_i
    x,y,w,h = cv2.boundingRect(c)
    mx,my = int(w*0.1), int(h*0.1)
    x,y = max(0,x-mx), max(0,y-my)
    w,h = min(w_i-x,w+2*mx), min(h_i-y,h+2*my)
    return x,y,w,h

def enhance_image(img):
    lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
    l,a,b = cv2.split(lab)
    l = cv2.createCLAHE(clipLimit=2.5, tileGridSize=(8,8)).apply(l)
    enh = cv2.cvtColor(cv2.merge((l,a,b)), cv2.COLOR_LAB2BGR)
    den = cv2.fastNlMeansDenoisingColored(enh, None, 3,3,7,21)
    return cv2.filter2D(den, -1, np.array([[0,-1,0],[-1,5,-1],[0,-1,0]]))

def preprocess_nail_image(path, size=(224,224)):
    img = cv2.imread(path)
    x,y,w,h = detect_nail_region(img)
    crop = img[y:y+h, x:x+w]
    final = cv2.resize(enhance_image(crop), size)
    return img, crop, final

sample_paths = [os.path.join(TEST_DIR, c, os.listdir(os.path.join(TEST_DIR, c))[0]) for c in ["clubbing","fungal_infection","psoriasis"]]
fig, axes = plt.subplots(3,3, figsize=(10,12))
for i,p in enumerate(sample_paths):
    o,c,f = preprocess_nail_image(p)
    for j,(im,t) in enumerate([(o,"Original"),(c,"Cropped"),(f,"Enhanced")]):
        axes[i,j].imshow(cv2.cvtColor(im, cv2.COLOR_BGR2RGB)); axes[i,j].set_title(t); axes[i,j].axis("off")
plt.tight_layout(); plt.savefig("preprocessing_demo.png"); plt.show()
print("Objective 1 done!")

labels = train_gen.classes
cw = compute_class_weight(class_weight="balanced", classes=np.unique(labels), y=labels)
class_weights = dict(enumerate(cw))
print("Class weights:", {class_names[i]: round(w,2) for i,w in class_weights.items()})

base_model = MobileNetV2(input_shape=(*IMG_SIZE,3), include_top=False, weights="imagenet")
base_model.trainable = False
x = GlobalAveragePooling2D()(base_model.output)
x = Dropout(0.3)(x); x = Dense(128, activation="relu")(x); x = Dropout(0.2)(x)
predictions = Dense(NUM_CLASSES, activation="softmax")(x)
model = Model(inputs=base_model.input, outputs=predictions)
model.compile(optimizer=Adam(1e-3), loss="categorical_crossentropy", metrics=["accuracy"])
print("Model built!")

callbacks = [
    tf.keras.callbacks.EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True),
    tf.keras.callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=3, min_lr=1e-6),
    tf.keras.callbacks.ModelCheckpoint("best_model_stage1.keras", monitor="val_accuracy", save_best_only=True),
]
history1 = model.fit(train_gen, validation_data=val_gen, epochs=15, class_weight=class_weights, callbacks=callbacks)

base_model.trainable = True
for layer in base_model.layers[:-30]: layer.trainable = False
model.compile(optimizer=Adam(1e-5), loss="categorical_crossentropy", metrics=["accuracy"])
callbacks2 = [
    tf.keras.callbacks.EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True),
    tf.keras.callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=3, min_lr=1e-7),
    tf.keras.callbacks.ModelCheckpoint("best_model_finetuned.keras", monitor="val_accuracy", save_best_only=True),
]
history2 = model.fit(train_gen, validation_data=val_gen, epochs=10, class_weight=class_weights, callbacks=callbacks2)
model.save("nail_disease_mobilenetv2_final.keras")
print("Final model saved!")

test_gen.reset()
y_pred = np.argmax(model.predict(test_gen), axis=1)
y_true = test_gen.classes
print(classification_report(y_true, y_pred, target_names=class_names))

cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=class_names, yticklabels=class_names)
plt.xlabel("Predicted"); plt.ylabel("True"); plt.savefig("confusion_matrix.png"); plt.show()

test_loss, test_acc = model.evaluate(test_gen)
print(f"Test Accuracy: {test_acc:.4f}")

def make_gradcam_heatmap(img_array, model, layer_name="Conv_1"):
    grad_model = tf.keras.models.Model([model.inputs], [model.get_layer(layer_name).output, model.output])
    with tf.GradientTape() as tape:
        conv_out, preds = grad_model(img_array)
        idx = tf.argmax(preds[0])
        class_ch = preds[:, idx]
    grads = tape.gradient(class_ch, conv_out)
    pooled = tf.reduce_mean(grads, axis=(0,1,2))
    heatmap = conv_out[0] @ pooled[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)
    heatmap = tf.maximum(heatmap,0)/(tf.reduce_max(heatmap)+1e-8)
    return heatmap.numpy(), class_names[idx.numpy()]

def show_gradcam(path, model):
    img = tf.keras.preprocessing.image.load_img(path, target_size=IMG_SIZE)
    arr = tf.keras.preprocessing.image.img_to_array(img)
    batch = np.expand_dims(preprocess_input(arr.copy()), axis=0)
    hm, pred = make_gradcam_heatmap(batch, model)
    hm_r = tf.image.resize(hm[...,np.newaxis], IMG_SIZE).numpy().squeeze()
    overlay = np.clip(plt.cm.jet(hm_r)[...,:3]*255*0.4 + arr, 0, 255).astype("uint8")
    fig, ax = plt.subplots(1,2, figsize=(8,4))
    ax[0].imshow(arr.astype("uint8")); ax[0].set_title("Original"); ax[0].axis("off")
    ax[1].imshow(overlay); ax[1].set_title(f"Grad-CAM: {pred}"); ax[1].axis("off")
    plt.tight_layout(); plt.show()

for d in ["fungal_infection","psoriasis","clubbing","healthy_nail"]:
    dd = os.path.join(TEST_DIR, d)
    show_gradcam(os.path.join(dd, os.listdir(dd)[0]), model)

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()
with open("nail_disease_model.tflite", "wb") as f:
    f.write(tflite_model)
print("TFLite model saved!")

from google.colab import files
files.download("nail_disease_mobilenetv2_final.keras")
files.download("nail_disease_model.tflite")
files.download("confusion_matrix.png")
files.download("preprocessing_demo.png")

